backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'work'
    label: 'Work'
    folder: 'content/work'
    create: true
    media_folder: ''
    public_folder: ''
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Order"
        name: "order"
        widget: "number"
        default: 2
        value_type: "int"
        min: 1
        max: 101
        step: 1
      - label: "Links"
        name: "links"
        widget: "list"
        default: [""]
      - { label: 'Category', name: 'category', widget: 'hidden' , default: 'work'}
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime'}
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Brief', name: 'brief', widget: 'markdown', required: false}
      - { label: 'Solution', name: 'solution', widget: 'markdown', required: false}
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image'}
      - { label: 'Video', name: 'video', widget: 'file', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown', required: false}