backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: '/static/media'
public_folder: '/media'

display_url: https://olivermeredith-2.netlify.app

collections:
  - name: 'work'
    media_folder: ''
    public_folder: ''
    label: 'Work'
    folder: 'content/work'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        required: false
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Title", name: "alt", widget: "string", required: false }
          - { label: "Description", name: "alt", widget: "string", required: false }
      - label: "Order"
        name: "order"
        widget: "number"
        default: 2
        value_type: "int"
        min: 1
        max: 101
        step: 1
      - label: "Links"
        name: "links"
        widget: "list"
        default: [""]
      - { label: 'Category', name: 'category', widget: 'hidden' , default: 'work'}
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime'}
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image'}
      - { label: 'videoSrcURL', name: 'videoSrcURL', widget: 'string', hint: 'The embed link, not the default share link', required: false}
      - { label: 'Color', name: 'color', widget: 'color', required: false}
      - { label: 'Brief', name: 'brief', widget: 'markdown', required: false}
      - { label: 'Solution', name: 'solution', widget: 'markdown', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown', required: false}